name: _error
timestamp: 1589457543
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1589457538
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-9882: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-5472: Menu
  messages:
    system-messages-5770: 'System Messages'
  content:
    system-content-7252: 'Page Content'
  copyright:
    copyright-8641: Copyright
  spacer:
    spacer-4838: Spacer
  branding:
    branding-3897: Branding
  mobile-menu:
    mobile-menu-7608: Mobile-menu
inherit: {  }
