version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1589457538
layout:
  /header/:
    -
      - 'logo-2164 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-6927
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-2081
    -
      - system-content-4108
  /footer/:
    -
      - position-footer
    -
      - 'copyright-2810 40'
      - 'spacer-3613 30'
      - 'branding-3926 30'
  offcanvas:
    -
      - mobile-menu-9475
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
