version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1589457679
layout:
  /navigation/:
    -
      - system-messages-7972
    -
      - 'logo-9608 18'
      - 'menu-6409 82'
  /header/: {  }
  /intro/: {  }
  /features/: {  }
  /utility/: {  }
  /above/: {  }
  /testimonials/: {  }
  /expanded/: {  }
  /container-main/:
    -
      -
        'aside 25':
          -
            - position-position-4734
      -
        'mainbar 50':
          -
            - system-content-1587
      -
        'sidebar 25':
          -
            - position-position-3949
  /footer/:
    -
      - 'copyright-1736 25'
      - 'spacer-spacer-4622 20'
      - 'social-2758 30'
      - 'totop-8670 25'
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    attributes:
      boxed: ''
      class: ''
  intro:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  aside:
    attributes:
      class: ''
    block:
      fixed: '1'
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  offcanvas:
    attributes:
      boxed: ''
content:
  logo-9608:
    title: 'Logo / Image'
    attributes:
      url: 'http://localhost/drugiProjekatEP/wordpress/'
      image: ''
      height: ''
      link: '1'
      svg: ''
      text: 'Guitar shop'
      class: g-logo
    block:
      extra:
        -
          style: 'margin-top:5px;'
  menu-6409:
    attributes:
      menu: gitare
      base: /
      startLevel: '0'
  position-position-4734:
    title: Aside
    attributes:
      key: aside
  position-position-3949:
    title: Sidebar
    attributes:
      key: sidebar
  copyright-1736:
    attributes:
      date:
        start: '2012'
      owner: 'Guitar Shop'
      additional:
        text: ''
  social-2758:
    attributes:
      display: both
      items:
        -
          icon: 'fa fa-phone fa-fw'
          text: '0659241192'
          title: ''
          link: ''
          name: 'Telefon:'
        -
          icon: 'fa fa-home'
          text: 'Veljka Dugosevica 16'
          title: ''
          link: ''
          name: 'Adresa:'
  totop-8670:
    title: 'To Top'
    attributes:
      content: 'Na vrh stranice'
