name: _body_only
timestamp: 1589457543
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1589457538
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-2592: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-7876: Menu
  messages:
    system-messages-3974: 'System Messages'
  content:
    system-content-9784: 'Page Content'
  copyright:
    copyright-1686: Copyright
  spacer:
    spacer-1722: Spacer
  branding:
    branding-8291: Branding
  mobile-menu:
    mobile-menu-4036: Mobile-menu
inherit: {  }
