version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1589457538
layout:
  /header/:
    -
      - 'logo-2592 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-7876
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-3974
    -
      - system-content-9784
  /footer/:
    -
      - position-footer
    -
      - 'copyright-1686 40'
      - 'spacer-1722 30'
      - 'branding-8291 30'
  offcanvas:
    -
      - mobile-menu-4036
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
