name: home
timestamp: 1589457542
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1589457538
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  showcase: Showcase
  feature: Feature
  subfeature: Subfeature
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  menu:
    menu-8692: Menu
  sample:
    sample-1: 'Gantry 5'
    sample-2: 'Getting Started'
    sample-3: 'Key Features'
  messages:
    system-messages-1925: 'System Messages'
  position:
    position-footer: Footer
  copyright:
    copyright-9386: Copyright
  social:
    social-8371: Social
  branding:
    branding-7533: Branding
  mobile-menu:
    mobile-menu-3445: 'Mobile Menu'
inherit: {  }
